version: "3"

services:
  api:
    build:
      context: .
      args: 
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: bash -c "gunicorn -w $MAX_NUMBER_OF_JOB -b 0.0.0.0:5000 app:app --timeout 300 --reload --log-level debug & ./bash/computation.sh ${MAX_NUMBER_OF_JOB} & python ./utils/update_status.py"    
    container_name: alligator_api
    env_file:
      - ./.env
    environment:
      FLASK_DEBUG: 1
    ports:
      - "${ALLIGATOR_PORT}:5000"
    restart: always
    volumes:
      - ./api:/code
      
  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "alligator_mongo"
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
      
  redis:
    image: redis:alpine
    container_name: alligator_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always  
    volumes:
      - './redis-data:/data'   
